# Generated by Django 4.2 on 2023-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_alter_customer_id_alter_orders_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='days',
            new_name='hours',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
