# Generated by Django 4.2 on 2023-07-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_alter_area_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='cost_per_hour',
            field=models.FloatField(default=2000),
        ),
    ]
